version: 2
updates:
  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps)"
    groups:
      ui-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps)"
    groups:
      api-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci(deps)"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /ui
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build(deps)"
