services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    restart: always

  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ui
